/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CalculadoraTeste3;

/**
 *
 * @author Felipe Boos
 */

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;

public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnCE = new javax.swing.JButton();
        jBtnZero = new javax.swing.JButton();
        jBtnIgual = new javax.swing.JButton();
        jBtnSomar = new javax.swing.JButton();
        jBtnUm = new javax.swing.JButton();
        jBtnDois = new javax.swing.JButton();
        jBtnTres = new javax.swing.JButton();
        jBtnSubtrair = new javax.swing.JButton();
        jBtnQuatro = new javax.swing.JButton();
        jBtnCinco = new javax.swing.JButton();
        jBtnSeis = new javax.swing.JButton();
        jBtnMultiplicar = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnOito = new javax.swing.JButton();
        jBtnNove = new javax.swing.JButton();
        jBtnDividir = new javax.swing.JButton();
        jBtnSete = new javax.swing.JButton();
        jLResultado = new javax.swing.JLabel();
        jLTextoAcima = new javax.swing.JLabel();
        jBtnVirgula = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnCE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnCE.setText("CE");
        jBtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCEActionPerformed(evt);
            }
        });

        jBtnZero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnZero.setText("0");
        jBtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZeroActionPerformed(evt);
            }
        });

        jBtnIgual.setBackground(new java.awt.Color(0, 180, 50));
        jBtnIgual.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBtnIgual.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIgual.setText("=");
        jBtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIgualActionPerformed(evt);
            }
        });

        jBtnSomar.setBackground(new java.awt.Color(150, 150, 150));
        jBtnSomar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnSomar.setText("+");
        jBtnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSomarActionPerformed(evt);
            }
        });

        jBtnUm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnUm.setText("1");
        jBtnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUmActionPerformed(evt);
            }
        });

        jBtnDois.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnDois.setText("2");
        jBtnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoisActionPerformed(evt);
            }
        });

        jBtnTres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnTres.setText("3");
        jBtnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTresActionPerformed(evt);
            }
        });

        jBtnSubtrair.setBackground(new java.awt.Color(150, 150, 150));
        jBtnSubtrair.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBtnSubtrair.setText("-");
        jBtnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtrairActionPerformed(evt);
            }
        });

        jBtnQuatro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnQuatro.setText("4");
        jBtnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuatroActionPerformed(evt);
            }
        });

        jBtnCinco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnCinco.setText("5");
        jBtnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCincoActionPerformed(evt);
            }
        });

        jBtnSeis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnSeis.setText("6");
        jBtnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeisActionPerformed(evt);
            }
        });

        jBtnMultiplicar.setBackground(new java.awt.Color(150, 150, 150));
        jBtnMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnMultiplicar.setText("x");
        jBtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplicarActionPerformed(evt);
            }
        });

        jBtnC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });

        jBtnOito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnOito.setText("8");
        jBtnOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOitoActionPerformed(evt);
            }
        });

        jBtnNove.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnNove.setText("9");
        jBtnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNoveActionPerformed(evt);
            }
        });

        jBtnDividir.setBackground(new java.awt.Color(150, 150, 150));
        jBtnDividir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnDividir.setText("÷");
        jBtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDividirActionPerformed(evt);
            }
        });

        jBtnSete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnSete.setText("7");
        jBtnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeteActionPerformed(evt);
            }
        });

        jLResultado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLResultado.setText("0");
        jLResultado.setVerifyInputWhenFocusTarget(false);

        jLTextoAcima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLTextoAcima.setForeground(new java.awt.Color(100, 100, 100));
        jLTextoAcima.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLTextoAcima.setText(" ");

        jBtnVirgula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnVirgula.setText(",");
        jBtnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVirgulaActionPerformed(evt);
            }
        });

        jBtnDelete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnDelete.setText("←");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(jBtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLTextoAcima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLTextoAcima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnSubtrair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DecimalFormatSymbols simbolosBrasil = new DecimalFormatSymbols(new Locale("pt", "BR"));
    
    DecimalFormat formatador = new DecimalFormat("#,##0.00", simbolosBrasil);
    
    double num1 = 0;
    double num2 = 0;
    double resultado = 0;
    String operador = " ";
    
    public void adicionarNumero(String numeroOuVirgula){
        String numAnterior = jLResultado.getText();
        
        String numAtualizado;
        
        if (numAnterior.equals("0") && !numeroOuVirgula.equals(",")){
            numAtualizado = numeroOuVirgula;
        } else {
            numAtualizado = numAnterior + numeroOuVirgula;
        }
        
        jLResultado.setText(numAtualizado);
    }
    
    public void setNum1(){
        String numero = jLResultado.getText();
        
        String numeroComPonto = numero.replace(",", ".");
        
        num1 = Double.valueOf(numeroComPonto);
        jLResultado.setText("0");
    }
    
    public void setNum2(){
        String numero = jLResultado.getText();
        
        String numeroComPonto = numero.replace(",", ".");
        
        num2 = Double.valueOf(numeroComPonto);
    }
    
    public void escreverTextoAcima(){
        String strNum1 = Double.toString(num1);
        
        jLTextoAcima.setText(strNum1 + operador);
        
    }
    
    private void jBtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIgualActionPerformed
        setNum2();
        resultado = 0;
        
        switch (operador){
            case "+":
                resultado = num1 + num2;
                break;
            case "-":
                resultado = num1 - num2;
                break;
            case "x":
                resultado = num1 * num2;
                break;
            case "÷":
                resultado = num1 / num2;
                break;
                
            default:
                break;
        }
        
        jLResultado.setText(Double.toString(resultado));
        jLTextoAcima.setText("");
        
    }//GEN-LAST:event_jBtnIgualActionPerformed

    private void setOperador(String strOperador){
        setNum1();
        operador = strOperador;
        escreverTextoAcima();
    }
    private void jBtnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSomarActionPerformed
        setOperador("+");
    }//GEN-LAST:event_jBtnSomarActionPerformed

    private void jBtnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTresActionPerformed
        adicionarNumero("3");
    }//GEN-LAST:event_jBtnTresActionPerformed

    private void jBtnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtrairActionPerformed
        setOperador("-");
    }//GEN-LAST:event_jBtnSubtrairActionPerformed

    private void jBtnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeisActionPerformed
        adicionarNumero("6");
    }//GEN-LAST:event_jBtnSeisActionPerformed

    private void jBtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplicarActionPerformed
        setOperador("x");
    }//GEN-LAST:event_jBtnMultiplicarActionPerformed

    private void jBtnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNoveActionPerformed
        adicionarNumero("9");
    }//GEN-LAST:event_jBtnNoveActionPerformed

    private void jBtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDividirActionPerformed
        setOperador("÷");
    }//GEN-LAST:event_jBtnDividirActionPerformed

    private void jBtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZeroActionPerformed
        adicionarNumero("0");
    }//GEN-LAST:event_jBtnZeroActionPerformed

    private void jBtnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUmActionPerformed
        adicionarNumero("1");
    }//GEN-LAST:event_jBtnUmActionPerformed

    private void jBtnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoisActionPerformed
        adicionarNumero("2");
    }//GEN-LAST:event_jBtnDoisActionPerformed

    private void jBtnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuatroActionPerformed
        adicionarNumero("4");
    }//GEN-LAST:event_jBtnQuatroActionPerformed

    private void jBtnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCincoActionPerformed
        adicionarNumero("5");
    }//GEN-LAST:event_jBtnCincoActionPerformed

    private void jBtnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVirgulaActionPerformed
        if (!jLResultado.getText().contains(",") && !jLResultado.getText().contains(".")){
            adicionarNumero(",");
        }
    }//GEN-LAST:event_jBtnVirgulaActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        String strResultado = jLResultado.getText();
        
        String novaString = strResultado.substring(0, strResultado.length() - 1);
        
        if (novaString.equals("")){
            jLResultado.setText("0");
        } else {
            jLResultado.setText(novaString);
        }
        
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeteActionPerformed
        adicionarNumero("7");
    }//GEN-LAST:event_jBtnSeteActionPerformed

    private void jBtnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOitoActionPerformed
        adicionarNumero("8");
    }//GEN-LAST:event_jBtnOitoActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        jLResultado.setText("0");
        jLTextoAcima.setText(" ");
        num1 = 0;
        num2 = 0;
        resultado = 0;
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCEActionPerformed
        num2 = 0;
        jLResultado.setText("0");
    }//GEN-LAST:event_jBtnCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCE;
    private javax.swing.JButton jBtnCinco;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnDividir;
    private javax.swing.JButton jBtnDois;
    private javax.swing.JButton jBtnIgual;
    private javax.swing.JButton jBtnMultiplicar;
    private javax.swing.JButton jBtnNove;
    private javax.swing.JButton jBtnOito;
    private javax.swing.JButton jBtnQuatro;
    private javax.swing.JButton jBtnSeis;
    private javax.swing.JButton jBtnSete;
    private javax.swing.JButton jBtnSomar;
    private javax.swing.JButton jBtnSubtrair;
    private javax.swing.JButton jBtnTres;
    private javax.swing.JButton jBtnUm;
    private javax.swing.JButton jBtnVirgula;
    private javax.swing.JButton jBtnZero;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLTextoAcima;
    // End of variables declaration//GEN-END:variables
}
